# Generated by Django 2.2.5 on 2019-09-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_askaquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskAQuestion',
        ),
    ]
