# Generated by Django 2.2.5 on 2019-09-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_askaquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
